sonar.host.url=https://sonarcloud.io
sonar.projectKey=learninglang-final
sonar.organization=omerebubekir
sonar.token=04d7f7423033c41ac65ffd198fafd8944467b9fc
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**
sonar.sourceEncoding=UTF-8